### ISSUE TITLE
Error initializing Agent

### ISSUE THREAD

**Issue by Pineyless** [damoeb/feedless#32]
Full code of my attempt to raise feedless with docker
(btw, on website it also says 

> no agents available

 in red)

`Skipping DNS check
2023.03.04
Starting core with profiles prod,root,prod
11:44:54,803 |-INFO in ch.qos.logback.classic.LoggerContext[default] - This is logback-classic version 1.4.11
11:44:54,811 |-INFO in ch.qos.logback.classic.util.ContextInitializer@1936f0f5 - No custom configurators were discovered as a service.
11:44:54,812 |-INFO in ch.qos.logback.classic.util.ContextInitializer@1936f0f5 - Trying to configure with ch.qos.logback.classic.joran.SerializedModelConfigurator
11:44:54,816 |-INFO in ch.qos.logback.classic.util.ContextInitializer@1936f0f5 - Constructed configurator of type class ch.qos.logback.classic.joran.SerializedModelConfigurator
11:44:54,858 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.scmo]
11:44:54,859 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.scmo]
11:44:54,868 |-INFO in ch.qos.logback.classic.util.ContextInitializer@1936f0f5 - ch.qos.logback.classic.joran.SerializedModelConfigurator.configure() call lasted 45 milliseconds. ExecutionStatus=INVOKE_NEXT_IF_ANY
11:44:54,868 |-INFO in ch.qos.logback.classic.util.ContextInitializer@1936f0f5 - Trying to configure with ch.qos.logback.classic.util.DefaultJoranConfigurator
11:44:54,870 |-INFO in ch.qos.logback.classic.util.ContextInitializer@1936f0f5 - Constructed configurator of type class ch.qos.logback.classic.util.DefaultJoranConfigurator
11:44:54,871 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
11:44:54,873 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/usr/feedless/app.jar!/BOOT-INF/classes!/logback.xml]
11:44:54,893 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@6615435c - URL [jar:file:/usr/feedless/app.jar!/BOOT-INF/classes!/logback.xml] is not of type file
11:44:55,095 |-INFO in ch.qos.logback.core.model.processor.TimestampModelHandler - Using current interpretation time, i.e. now, as time reference.
11:44:55,099 |-INFO in ch.qos.logback.core.model.processor.TimestampModelHandler - Adding property to the context with key="timestamp-by-second" and value="20240629T114455" to the LOCAL scope
11:44:55,102 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - Processing appender named [Console-Appender]
11:44:55,102 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
11:44:55,116 |-INFO in ch.qos.logback.core.model.processor.ImplicitModelHandler - Assuming default type [ch.qos.logback.classic.PatternLayout] for [layout] property
11:44:55,152 |-WARN in ch.qos.logback.core.ConsoleAppender[Console-Appender] - This appender no longer admits a layout as a sub-component, set an encoder instead.
11:44:55,153 |-WARN in ch.qos.logback.core.ConsoleAppender[Console-Appender] - To ensure compatibility, wrapping your layout in LayoutWrappingEncoder.
11:44:55,153 |-WARN in ch.qos.logback.core.ConsoleAppender[Console-Appender] - See also http://logback.qos.ch/codes.html#layoutInsteadOfEncoder for details
11:44:55,153 |-INFO in ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [Console-Appender] to Logger[ROOT]
11:44:55,159 |-INFO in ch.qos.logback.core.model.processor.DefaultProcessor@3ffc5af1 - End of configuration.
11:44:55,160 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@26653222 - Registering current configuration as safe fallback point
11:44:55,161 |-INFO in ch.qos.logback.classic.util.ContextInitializer@1936f0f5 - ch.qos.logback.classic.util.DefaultJoranConfigurator.configure() call lasted 291 milliseconds. ExecutionStatus=DO_NOT_INVOKE_NEXT_IF_ANY
11:44:55,700 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@d706f19 - URL [jar:file:/usr/feedless/app.jar!/BOOT-INF/classes!/logback.xml] is not of type file
11:44:55,706 |-INFO in ch.qos.logback.core.model.processor.TimestampModelHandler - Using current interpretation time, i.e. now, as time reference.
11:44:55,706 |-INFO in ch.qos.logback.core.model.processor.TimestampModelHandler - Adding property to the context with key="timestamp-by-second" and value="20240629T114455" to the LOCAL scope
11:44:55,706 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - Processing appender named [Console-Appender]
11:44:55,706 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
11:44:55,707 |-INFO in ch.qos.logback.core.model.processor.ImplicitModelHandler - Assuming default type [ch.qos.logback.classic.PatternLayout] for [layout] property
11:44:55,708 |-WARN in ch.qos.logback.core.ConsoleAppender[Console-Appender] - This appender no longer admits a layout as a sub-component, set an encoder instead.
11:44:55,708 |-WARN in ch.qos.logback.core.ConsoleAppender[Console-Appender] - To ensure compatibility, wrapping your layout in LayoutWrappingEncoder.
11:44:55,708 |-WARN in ch.qos.logback.core.ConsoleAppender[Console-Appender] - See also http://logback.qos.ch/codes.html#layoutInsteadOfEncoder for details
11:44:55,708 |-INFO in ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [Console-Appender] to Logger[ROOT]
11:44:55,708 |-INFO in ch.qos.logback.core.model.processor.DefaultProcessor@30b7c004 - End of configuration.
11:44:55,708 |-INFO in org.springframework.boot.logging.logback.SpringBootJoranConfigurator@79efed2d - Registering current configuration as safe fallback point
11:44:55,718 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@7a4ccb53 - Propagating ERROR level on Logger[ROOT] onto the JUL framework
11:44:55,719 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@7a4ccb53 - Propagating OFF level on Logger[ch.qos.logback] onto the JUL framework
11:44:55,720 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@7a4ccb53 - Propagating ERROR level on Logger[com.netflix] onto the JUL framework
11:44:59.342 ERROR o.s.boot.SpringApplication - Application run failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'webToFeedTransformer' defined in URL [jar:file:/usr/feedless/app.jar!/BOOT-INF/classes!/org/migor/feedless/web/WebToFeedTransformer.class]: Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'propertyService': Invocation of init method failed
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:801)
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:240)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1352)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1189)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:973)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:950)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:616)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:733)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:435)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:311)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1290)
        at org.migor.feedless.RichRssApplicationKt.main(RichRssApplication.kt:34)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:95)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'propertyService': Invocation of init method failed
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:222)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:419)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1762)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:598)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1417)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1337)
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:910)
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:788)
        ... 25 common frames omitted
Caused by: java.lang.IllegalArgumentException: jwtSecret seems invalid
        at org.springframework.util.Assert.isTrue(Assert.java:122)
        at org.migor.feedless.common.PropertyService.onInit(PropertyService.kt:55)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMethod.invoke(InitDestroyAnnotationBeanPostProcessor.java:457)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:401)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:219)
        ... 38 common frames omitted`

**Comment by BrahimAkar** [comment]
Same issue 😢
